spring:
    application:
        name: spring-cloud-gateway
    profiles:
        active: dev
    config:
        import: "zookeeper:wsl2:2181"
    cloud:
        zookeeper:
            config:
                enabled: true
                root: spring-cloud-config
                profileSeparator: ":"