server:
    port: 2000
management:
    gateway:
        enabled: true
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"
spring:
    zipkin:
        baseUrl: http://wsl2:9411
    cloud:
        gateway:
            globalcors:
                add-to-simple-url-handler-mapping: true
#                cors-configurations:
#                    "[/**]":
#                        allowedOrigins: "https://docs.spring.io"
#                        allowedMethods:
#                            - GET
            httpclient:
                connect-timeout: 10000
                response-timeout: 30s
            discovery:
                locator:
                    enabled: true
                    predicates:
                        - Path='/v1/'+ serviceId + '/**'
                    filters:
                        - PreserveHostHeader
                        - name: CircuitBreaker
                          args:
                              name: serviceId
                              fallbackUri: "forward:/404"
                              statusCodes:
                                  - 404
                        - RewritePath='/v1/' + serviceId + '/(?<remaining>.*)', '/v1/${remaining}'