server:
    port: 2000
management:
    endpoints:
        web:
            exposure:
                include: "*"
spring:
    application:
        name: spring-cloud-config-server
    profiles:
        active: native, dev
    cloud:
        config:
            server:
                native:
                    searchLocations: classpath:/config